<a href="https://colab.research.google.com/github/mohit-singh4180/-ecommerce_microServices/blob/master/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Template

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [9]:
### Cleaning the data-remove 1 percent of missing data or handle missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.NAN, strategy='mean')
###Specify age and salary column
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
### Encode categorical data 
###replace country name to 0 1 and 2 and purchase column with 0 and 1 using Label Encoder

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)



In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
### Encode categorical data more than 2 values
### using- one hot encoding string to integer(binary vector)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X=np.array(ct.fit_transform(X))









In [12]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
X_train

array([[1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [18]:
X_test

array([[1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [19]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [20]:
y_test

array([0, 0])

Feature Scaling

In [21]:
### Apply after split to avoid info leakage because of test data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
###to non encoded value
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [22]:
print (X_train)

[[1.0 0.0 1.0 -0.7745966692414834 0.2630675731713538 0.1238147854838185]
 [0.0 1.0 0.0 -0.7745966692414834 -0.25350147960148617 0.4617563176278856]
 [1.0 0.0 0.0 1.2909944487358056 -1.9753983221776195 -1.5309334063940294]
 [1.0 0.0 0.0 1.2909944487358056 0.05261351463427101 -1.1114197802841526]
 [0.0 1.0 0.0 -0.7745966692414834 1.6405850472322605 1.7202971959575162]
 [1.0 0.0 0.0 1.2909944487358056 -0.08131179534387283
  -0.16751412153692966]
 [0.0 1.0 0.0 -0.7745966692414834 0.9518263102018072 0.9861483502652316]
 [0.0 1.0 0.0 -0.7745966692414834 -0.5978808481167128
  -0.48214934111933727]]


In [23]:
print (X_test)

[[1.0 0.0 1.0 -0.7745966692414834 -1.4588292694047795 -0.9016629672292141]
 [1.0 0.0 1.0 -0.7745966692414834 1.984964415747487 2.139810822067393]]
